[project]
name = "stockmcpservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.14.1",
    "fastmcp>=3.4.2",
    "isort>=8.0.1",
    "mypy>=2.1.0",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "prefab-ui>=0.20.2",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.15.16",
    "ta>=0.11.0",
    "yfinance>=1.4.1",
]
